version: '3.8'

services:
  auth:
    build: ./auth
    expose:
      - "3000"
    env_file:
      - ./auth/.env
    networks:
      - postgre_booktook_net

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    expose:
      - "8080"
    networks:
      - postgre_booktook_net
    depends_on:
      - auth

  frontend:
    build: ./frontend
    expose:
      - "80"
    networks:
      - postgre_booktook_net

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth
      - backend
      - frontend
    networks:
      - postgre_booktook_net

networks:
  postgre_booktook_net:
    external: true  